set -g default-terminal "tmux-256color"
# Нумерация окон начинается с 1 (по-умолчанию с 0)
set -g base-index 1
# Нумерация панелей начинается с 1 (по-умолчанию с 0)
setw -g pane-base-index 1

# Удалить все быстрые клавиши без Ctrl+B
unbind -a -T root
# Задаем быстрые клавиши без использования Ctl+B
bind -n M-F5 source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"
bind -n M-Enter new-window
bind -n M-h split-window -v
bind -n M-v split-window -h

set -g @tmux-gruvbox-right-status-x "%d-%m-%y"
set -g @tmux-gruvbox-right-status-z " "

# Подключаем плагины
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'
run '~/.config/tmux/plugins/tpm/tpm'

#set -g pane-border-lines double
set -g pane-border-style fg=gray
set -g pane-active-border-style fg=gray

